"""Contenido inicial de demostración. Requiere validación curricular del docente."""
from pedagogy import enrich, case_photo
STATIONS = ['Contextualización','Aprendizajes esperados','Situación integradora','Evaluación final','Retroalimentación y cierre']
STEPS = ['Analizar','Comprender','Relacionar','Aplicar y decidir','Verificar','Retroalimentar']
AES = [
 {'title':'Interpreta la simbología de equipos y cañerías en planos.', 'description':'Relaciona la leyenda del plano con los equipos, las conexiones y el recorrido de las tuberías.', 'steps':[
 'Observa una leyenda con UE (unidad exterior), UI (unidad interior) y dos trazos que unen ambas. Identifica qué información entrega y qué información falta.',
 'UE y UI identifican equipos; la leyenda explica las líneas. Explica por qué un color de línea por sí solo no basta para identificar una tubería.',
 'En una sala hay una UI conectada a una UE en la cubierta. Relaciona esta distribución con las etiquetas que esperarías encontrar en el plano.',
 'Dos líneas se cruzan y no se indica unión. Explica cómo comprobarías si están conectadas antes de interpretar el recorrido.',
 'Compara las etiquetas UE-01 y UI-01 en la planta y en el esquema. Describe dos verificaciones para evitar confundir equipos.',
 'Revisa tus respuestas. Explica qué error de interpretación podrías cometer y qué recurso te ayudaría a corregirlo.']},
 {'title':'Identifica accesorios y elementos complementarios en los planos.', 'description':'Reconoce soportes, desagües y elementos de control como partes de un proyecto coordinado.', 'steps':[
 'En el proyecto aparecen soportes, un drenaje y un control de temperatura. Clasifica qué función cumple cada uno.',
 'Un accesorio no siempre aparece dibujado a escala. Explica cómo usarías la leyenda y las especificaciones para identificarlo.',
 'Relaciona la ubicación del drenaje con el recinto y el recorrido representado. ¿Qué información necesitarías confirmar?',
 'La ubicación propuesta del control no coincide entre dos planos. Justifica qué harías antes de escoger una ubicación.',
 'Prepara una lista de tres comprobaciones para verificar que los accesorios identificados estén incluidos en el listado de materiales.',
 'Describe una omisión que detectaste o podrías detectar y cómo comunicarías la corrección al equipo.']},
 {'title':'Relaciona componentes del sistema en planos.', 'description':'Integra equipos, conexiones y documentación para explicar el funcionamiento representado.', 'steps':[
 'Identifica los equipos, recorridos y referencias de detalle que necesitas para comprender el sistema completo.',
 'Explica la diferencia entre una planta de ubicación y un esquema de conexiones. ¿Qué aporta cada representación?',
 'Relaciona UE-01, UI-01 y su control con la leyenda del proyecto. Explica cómo rastrearías cada elemento entre documentos.',
 'El recorrido atraviesa un espacio reservado a otro proyecto. Formula una consulta de coordinación con la información necesaria.',
 'Explica cómo verificarías que la versión del plano, las etiquetas y el listado de materiales son coherentes.',
 'Resume tu procedimiento de lectura de planos y plantea una mejora concreta para tu próxima revisión.']}
]
from pedagogy import case_photo
CASES = [
 {'title':'Leyenda incompleta en la sala de 3°','site':'Liceo TP · Maipú · sala 3° medio','lead':'Cassette en aula · planta sin leyenda completa','pressure':'El inspector de la obra llega a las 11:00 y pide conformidad de la sala para el consejo de curso.','prompt':'Una línea discontinua aparece en la planta de la sala, pero no en la leyenda.','context':'Recibes el dossier de climatización de la sala de 3° medio: planta R-B, una leyenda parcial y el listado de equipos. En el techo ya está la cassette UI-01. En la planta hay un trazo discontinuo que cruza el recinto, pero esa línea no aparece en la leyenda. El color se parece al del drenaje y también al de una tubería de líquido. Si asignas una función solo por el color, el montaje de la tarde puede conectar mal el desagüe sobre el pizarrón.','correct':'Consultar la leyenda y pedir aclaración documentada','wrong':'Asignar una función por su color','alt':'Aula de liceo con cassette de techo. La evidencia del caso está en la planta y la leyenda, no en el color de la línea.'},
 {'title':'Dos recintos, la misma etiqueta','site':'Clínica dental · Ñuñoa · boxes 2 y 3','lead':'UI-01 repetida en dos boxes','pressure':'La clínica abre a las 08:30 y el esterilizado no puede quedar sin clima.','prompt':'Dos unidades interiores aparecen como UI-01 en recintos distintos.','context':'El proyecto contempla un split por box. En planta, el box 2 y el box 3 aparecen ambos como UI-01. El listado declara una sola UI-01 asociada a UE-01 en cubierta. El pasillo clínico ya tiene la rejilla de impulsión instalada. Si das por hecho que es el mismo equipo, mañana se pide un evaporador que no está comprado o se deja un box sin unidad.','correct':'Registrar la duplicación y contrastar el listado de equipos','wrong':'Dar por hecho que es un único equipo','alt':'Pasillo de clínica con rejilla de climatización. El hallazgo es una etiqueta UI-01 duplicada entre recintos.'},
 {'title':'Cruce sobre la línea de lácteos','site':'Supermercado · San Miguel · góndola refrigerada','lead':'Tubería versus conducto sin cotas','pressure':'El gerente amenaza con cortar el montaje si «se toca el frío de los lácteos».','prompt':'Una tubería cruza un conducto en la planta de la góndola refrigerada.','context':'En planta, la tubería de líquido de las vitrinas cruza el conducto de retorno de la sala de ventas. No hay sección ni cotas de altura. El pasillo de lácteos ya está en 4 °C y no se puede parar la cadena de frío «por si acaso». Un cruce dibujado no prueba colisión, pero tampoco autoriza a seguir.','correct':'Revisar cotas y secciones para comprobar interferencias','wrong':'Suponer que ambos están a la misma altura','alt':'Pasillo de lácteos con vitrinas refrigeradas. El cruce de tubería y conducto no tiene cotas de altura.'},
 {'title':'Dos revisiones y una inauguración','site':'Hotel boutique · Providencia · cubierta','lead':'Planta R-C versus listado R-A','pressure':'La gerencia prometió check-in el viernes y pide «cerrar el plano hoy».','prompt':'La planta es revisión C y el listado de materiales es revisión A.','context':'En la cubierta hay tres condensadoras nuevas. La planta vigente es revisión C (tres UE). El listado que llegó con la orden de compra es revisión A (dos UE). Los archivos pesan distinto y alguien sugiere usar «el más liviano». Si compras con el listado viejo, el viernes falta una unidad y el hall de recepción queda sin clima.','correct':'Comprobar cuál es la documentación vigente','wrong':'Usar siempre el archivo más pequeño','alt':'Cubierta de hotel con condensadoras. La planta y el listado no comparten la misma revisión.'},
 {'title':'El rack no deja pasar','site':'Oficina · Santiago Centro · closet de servidores','lead':'Equipo pegado al muro · acceso no dibujado','pressure':'TI exige no apagar el rack: «si se cae el correo, es tu responsabilidad».','prompt':'El equipo queda junto a un muro que no aparece en la planta original.','context':'El split de 9000 BTU quedó a 8 cm del rack. La ficha ficticia del ejercicio pide 30 cm de acceso lateral. La planta original muestra un pasillo que en terreno no existe: alguien corrió el muro de tabique. El equipo cabe, pero no se puede abrir el panel ni cambiar un filtro. Aprobar porque «ya está instalado» deja el closet sin mantención.','correct':'Contrastar el espacio con documentación del equipo y proyecto','wrong':'Mantener la ubicación sin revisar','alt':'Closet de servidores con split pegado al rack. El acceso de mantención no coincide con la planta.'},
 {'title':'El condensado no tiene destino','site':'Restaurant · Recoleta · cocina caliente','lead':'Cassette con drenaje sin descarga','pressure':'Sanidad revisa mañana y el piso ya tuvo una filtración sobre la cocina.','prompt':'El plano muestra el origen del drenaje, pero no su descarga.','context':'Sobre la cocina hay una cassette con el tubo de condensado visible. La planta marca el origen junto a UI-02 y después el trazo se corta. No hay pozo, ni desagüe de lavaplatos coordinado, ni pendiente declarada. El chef quiere que «lo tires al desagüe más cercano». Esa decisión no está en el proyecto y puede devolver olores a la sala.','correct':'Solicitar el recorrido y destino definidos en el proyecto','wrong':'Elegir el punto más próximo sin coordinación','alt':'Cocina de restaurant con cassette y tubo de condensado. El plano no define el destino del drenaje.'},
 {'title':'La copia no es el original','site':'Obra · Independencia · losa en bruto','lead':'Plano reducido · escala no verificada','pressure':'El capataz pide «las medidas ya» para puntear soportes antes del hormigón.','prompt':'Una copia impresa ha sido reducida respecto del original.','context':'En la mesa de la faena hay un plano de ductos impreso en A3. El cajetín dice 1:50, pero la copia se redujo para que cupiera en la impresora de la oficina. Un tramo de 6 cm «mide» distinto si usas una regla sobre esta hoja. Si marcas soportes con esa medida, el ducto no llega a la rejilla del pasillo.','correct':'Usar cotas indicadas y verificar la escala antes de medir','wrong':'Medir directamente con cualquier regla','alt':'Obra con ductos a la vista y un plano sobre la mesa. La copia impresa puede no conservar la escala del original.'},
 {'title':'El soporte no está en el listado','site':'Farmacia de barrio · La Florida · refrigerador 4 °C','lead':'Detalle con soporte · listado sin la pieza','pressure':'El visor marca 4,0 °C y no se puede mover el refrigerador con la vacuna adentro.','prompt':'Un soporte aparece en el detalle, pero no en el listado.','context':'El detalle D-02 muestra un soporte sísmico para el refrigerador de cadena de frío. El listado de materiales no lo incluye. El visor del equipo indica 4,0 °C. Si eliminas el soporte del detalle para «hacer cuadrar» el Excel, el anclaje queda fuera de la compra y el equipo sigue libre ante un sismo.','correct':'Registrar la diferencia y pedir conciliación documental','wrong':'Eliminar el soporte del detalle','alt':'Farmacia con refrigerador a 4,0 °C y planos sobre el mesón. Un soporte del detalle no está en el listado.'},
 {'title':'El control no sabe en qué muro vivir','site':'Oficina abierta · Las Condes · open plan','lead':'Termostato en dos muros distintos','pressure':'El cliente ya pintó y no quiere «otro hoyo en la tabiquería».','prompt':'Dos documentos ubican el control en muros diferentes.','context':'La planta R-2 pone el control de temperatura en el muro este, lejos de la cassette. El esquema de control R-1 lo dibuja en el muro oeste, junto a un ventanal con sol de tarde. Ninguno indica qué revisión manda. Elegir el muro «más cómodo» deja el sensor al sol o detrás de un escritorio.','correct':'Identificar versiones y solicitar una ubicación coordinada','wrong':'Elegir el muro que parezca más cómodo','alt':'Oficina abierta con cassettes de techo. Dos documentos ubican el control en muros distintos.'},
 {'title':'Falta el detalle D-04','site':'Bodega de vinos · Valle del Maipo','lead':'Planta remite a un detalle que no llegó','pressure':'La vendimia entra en diez días y la bodega debe quedar a 14 °C.','prompt':'La planta remite a D-04, que no está en los archivos recibidos.','context':'La planta de la cava indica «ver D-04» junto al evaporador de muro. En la carpeta digital no está D-04: hay D-01 a D-03 y D-05. Sin ese detalle no sabes el desagüe ni la distancia al barril. Inventar D-04 para no retrasar la visita deja una cavidad que puede gotear sobre la madera.','correct':'Solicitar el detalle faltante antes de concluir la revisión','wrong':'Inventar el contenido de D-04','alt':'Cava de vinos con equipo de clima en el muro. La planta cita el detalle D-04, que no está en los archivos.'},
 {'title':'Dos líneas, un solo color','site':'Terminal rural de buses · Rancagua','lead':'Líquido y succión pintados iguales','pressure':'El hall abre a las 06:00 y el trazado se pinta esta noche.','prompt':'Dos líneas paralelas tienen un mismo color.','context':'En el cielo del hall hay dos cañerías de cobre paralelas, ambas marcadas en planta con el mismo azul. La leyenda distingue líquido y succión por etiqueta, no por color. Si las identificas solo por el pintado, puedes aislar la línea equivocada y dejar la succión sudando sobre los asientos.','correct':'Revisar etiquetas, leyenda y especificaciones','wrong':'Identificarlas únicamente por el color','alt':'Hall de terminal con difusores en el cielo. Dos cañerías paralelas no se distinguen solo por el color.'},
 {'title':'La misma luz, dos medidas','site':'Packing de fruta · Rengo · cámara de manzanas','lead':'Cotas de 0,80 m y 1,10 m para el mismo vano','pressure':'El camión de bins llega a las 16:00 y la puerta no puede quedar «a ojo».','prompt':'La misma separación aparece con dos medidas distintas.','context':'El vano de la puerta de la cámara mide 0,80 m en la planta y 1,10 m en la elevación. Es el mismo vano, las mismas hojas, dos números. Promediar (0,95 m) fabrica una cota que no existe en ningún documento y la cortina de frío no calza.','correct':'Documentar la discrepancia y pedir confirmación','wrong':'Promediar ambas medidas','alt':'Cámara de packing con puerta aislada. La misma separación tiene dos cotas distintas en planta y elevación.'},
 {'title':'La bandeja eléctrica se tomó el trazado','site':'Mall · food court · cielo técnico abierto','lead':'Canalización eléctrica sobre el recorrido HVAC','pressure':'Electricidad cierra su tramo mañana y no quiere rehacer bandejas.','prompt':'La canalización eléctrica ocupa el recorrido del sistema.','context':'En el cielo del patio de comidas, la bandeja eléctrica cruza justo el eje donde la planta HVAC lleva el retorno. No hay consulta registrada. Si desvías el ducto por tu cuenta, sales del proyecto y puedes chocar con sprinklers. Si no dices nada, las dos especialidades se pelean el mismo metro.','correct':'Formular una consulta con ubicación y documentos afectados','wrong':'Modificar el trazado por iniciativa propia','alt':'Patio de comidas con cielo técnico. La bandeja eléctrica ocupa el recorrido previsto del sistema.'},
 {'title':'Cuatro unidades en planta, tres en la compra','site':'Gimnasio municipal · Puente Alto','lead':'Planta con cuatro cassettes · listado con tres','pressure':'El alcalde inaugura el sábado y el listado «ya se mandó a compra».','prompt':'La planta tiene cuatro unidades y el listado registra tres.','context':'La planta muestra UI-01 a UI-04 sobre la cancha. El listado trae tres cassettes y una UE. El recinto es grande: tres equipos no cubren los cuatro cuadrantes dibujados. Comprar tres «porque el Excel ya salió» deja un cuarto de la cancha sin impulsión y nadie podrá explicar dónde quedó UI-04.','correct':'Conciliar etiquetas y cantidades entre documentos','wrong':'Comprar tres unidades sin consultar','alt':'Gimnasio municipal con equipos altos en el muro. La planta declara cuatro unidades y el listado solo tres.'},
 {'title':'Tres fallas y la firma de las 18:00','site':'Oficina de faena · Lo Barnechea','lead':'Entrega de revisión con tres inconsistencias','pressure':'El mandante quiere tu firma hoy a las 18:00 «para no frenar hormigón».','prompt':'Ya identificaste tres inconsistencias en la documentación.','context':'En la oficina de faena tienes la planta, el listado y tres observaciones abiertas: una etiqueta duplicada, un drenaje sin destino y un detalle que no llegó. Te piden «avisa que el plano está malo» por WhatsApp y listo. Sin ubicación, evidencia y consulta, mañana nadie puede reconstruir qué viste ni quién debe responder.','correct':'Entregar un registro con ubicación, evidencia y consulta','wrong':'Comunicar solo que el plano está mal','alt':'Oficina de faena con planos, cascos y la obra al fondo. La entrega exige un registro trazable, no un recado.'},
]
for i,c in enumerate(CASES):
    c['image']=case_photo(i,c)
QUESTIONS = []
for n,c in enumerate(CASES):
 correct,wrong,context=c['correct'],c['wrong'],c['prompt']
 opts=[correct,wrong,'Continuar sin registrar la información faltante','Confiar en la apariencia del elemento y continuar sin dejar registro.']
 shift=n%4;opts=opts[shift:]+opts[:shift]
 QUESTIONS.append({'id':n,'question':context+' ¿Qué decisión permite una revisión fundada?', 'options':opts,'answer':opts.index(correct),'explanation':correct+'. La interpretación debe apoyarse en documentación verificable.','stimulus':c['lead'],'image':c['image']})
_DET_QUESTIONS = [
 ("En la copia, el vano mide 3 cm a 1:50 (1,5 m) y la elevación indica 0,8 m en el mismo vano. ¿Qué decisión tomas?",
  ['Registrar la inconsistencia y solicitar la revisión del dibujo','Registrar 0,8 m sin comentar la diferencia','Registrar 1,5 m y no revisar la elevación','Firmar la conformidad con el valor mayor'],
  'Registrar la inconsistencia y solicitar la revisión del dibujo',
  'El cálculo (1,5 m) y el dato de elevación (0,8 m) no coinciden; la decisión fundada es registrar la inconsistencia y pedir la revisión, no elegir un valor a favor.','Vano con cota contradictoria.'),
 ("Cuatro colegas proponen cómo cerrar la revisión. ¿Cuál decisión es la más fundada?",
  ['Solicitar el original y contrastarlo antes de aprobar','Firmar para no atrasar la obra','Borrar la cota dudosa sin avisar','Copiar el valor del listado sin revisar'],
  'Solicitar el original y contrastarlo antes de aprobar',
  'La decisión más fundada apoya la verificación contra el documento original; el resto improvisa sin evidencia.','Cierre de revisión en equipo.'),
 ("Recibes una copia sin rótulo verificado y con dos cotas distintas en el mismo vano. ¿Qué decisión tomas en primer lugar?",
  ['Verificar la escala y el rótulo antes de medir','Marcar de inmediato la cota mayor','Enviar el listado a compra','Pedir la firma del mandante'],
  'Verificar la escala y el rótulo antes de medir',
  'Antes de cualquier cálculo se controla la escala y el rótulo; medir primero arrastra el error.','Copia sin rótulo verificado.'),
 ("Mides 40 mm en una copia que dice 1:50, pero la leyenda pide dibujar a 1:100. ¿Qué decisión tomas antes de registrar?",
  ['Confirmar cuál es la escala válida y luego registrar','Usar 1:50 directamente','Usar 1:100 directamente','No registrar ninguna medición'],
  'Confirmar cuál es la escala válida y luego registrar',
  'Dos escalas señaladas exigen confirmar la válida antes de convertir; elegir sin controlar la escala propaga el error.','Escalas en conflicto.'),
 ("El plano muestra cuatro unidades y el listado de compra trae tres. ¿Qué decisión permite una compra coherente?",
  ['Conciliar el plano y el listado y registrar la diferencia','Comprar según el listado sin avisar','Comprar según el plano sin revisar','Comprar y completar después'],
  'Conciliar el plano y el listado y registrar la diferencia',
  'Una diferencia entre documentos se concilia antes de comprar; comprar sin resolver arrastra el error al pedido.','Compra con inconsistencia.'),
 ("Tu jefe pide firmar hoy un dibujo que aún no cuadra. ¿Qué decisión tomas?",
  ['Explicar la inconsistencia y proponer un plazo para revisar','Firmar hoy para cumplir el plazo','Firmar con una nota a pie','Ocultar el hallazgo y seguir'],
  'Explicar la inconsistencia y proponer un plazo para revisar',
  'Firmar un documento no verificado compromete la conformidad; la decisión responsable es comunicar y acordar la revisión.','Presión para firmar.'),
 ("La copia no indica su escala. ¿Qué decisión tomas para cubicar los materiales?",
  ['Solicitar el original o el dato de escala primero','Suponer que es 1:50','Medir y leer centímetros como metros','Descartar el plano sin avisar'],
  'Solicitar el original o el dato de escala primero',
  'Sin escala no hay conversión válida; la decisión fundada es pedir el dato de escala y no suponer.','Copia sin escala.'),
 ("Debes confirmar el recorrido del drenaje antes de firmar. ¿Qué decisión tomas sobre la documentación?",
  ['Solicitar planta, elevación y detalle del drenaje','Revisar solo la planta','Revisar solo el listado de equipos','No solicitar más información'],
  'Solicitar planta, elevación y detalle del drenaje',
  'Un recorrido se verifica con la planta, su elevación y el detalle; faltar uno deja la verificación incompleta.','Confirmar el drenaje.'),
 ("Antes de dar conformidad al plano, ¿qué decisión tomas?",
  ['Verificar contra el documento y controlar la escala','Firmar por la presión del plazo','Confiar en la apariencia del dibujo','Dejar la verificación pendiente'],
  'Verificar contra el documento y controlar la escala',
  'La conformidad se otorga tras verificar el documento y su escala; confiar en la apariencia no sustituye el control.','Conformidad del plano.'),
 ("En un proyecto nuevo sin leyenda completa, ¿qué decisión tomas para empezar a trabajar?",
  ['Solicitar la leyenda y el original antes de interpretar','Interpretar por convención y asumir','Tomar medidas sin leyenda','Ignorar la falta de leyenda'],
  'Solicitar la leyenda y el original antes de interpretar',
  'La leyenda define la simbología; ante una incompleta, la decisión correcta es pedirla antes de interpretar el plano.','Proyecto nuevo sin leyenda.'),
]
_n=15
for q,opts,good,expl,stim in _DET_QUESTIONS:
    QUESTIONS.append({'id':_n,'question':q,'options':opts,'answer':opts.index(good),'explanation':expl,'stimulus':stim,'image':case_photo(_n) if _n < len(CASES) else '/static/themes/plans.png'})
    _n+=1
DEVELOPMENT='En una sala de un liceo, la planta revisión B muestra dos unidades interiores UI-01 y UI-02 conectadas a UE-01. El listado revisión A incluye una sola unidad interior y no identifica el drenaje. Explica cómo revisarías la documentación, qué inconsistencias registrarías, qué información solicitarías y cómo verificarías la corrección antes de dar conformidad al plano. Fundamenta tu respuesta.'
RUBRIC=[{'name':'Identificación de inconsistencias','max':5},{'name':'Uso de leyenda, revisiones y documentos','max':5},{'name':'Relación entre componentes','max':5},{'name':'Decisiones justificadas y consulta','max':5},{'name':'Verificación y claridad de la respuesta','max':5}]
def _demo_case(i,c):
    fillers=['Continuar sin registrar la información faltante.','Confiar en la apariencia del elemento y continuar sin dejar registro.']
    opts=([c['correct'],c['wrong']] if i%2==0 else [c['wrong'],c['correct']])+fillers
    item={'title':c['title'],'context':c['context'],'options':opts,'answer':i%2,
          'site':c['site'],'lead':c['lead'],'pressure':c['pressure'],'image':c['image'],'alt':c['alt'],
          'stimulus':c['lead'],'question':'¿Qué decisión permite una revisión fundada?'}
    return item
DEFAULT_CONTENT=enrich({'aes':AES,'cases':[_demo_case(i,c) for i,c in enumerate(CASES)],'questions':QUESTIONS,'development':DEVELOPMENT,'context':'Un liceo necesita revisar el proyecto de climatización de una sala. Recibes planos, una leyenda y un listado de equipos. Tu misión en esta estación es comprender la documentación, identificar sus componentes y anticipar inconsistencias. No resuelvas ni cubiques todavía.','rubric':RUBRIC,'case_title':'Climatización en un edificio educacional','application':'En la revisión y coordinación de documentación técnica. Una etiqueta, una leyenda y una referencia de detalle deben contar la misma historia.','reflection_prompt':'¿Qué revisarías primero y qué información necesitarías confirmar?','practice':{'type':'scale','title':'Explorador de escalas'}},1)
