"""Encargos largos para cubrir el 30 % de HP por módulo. Estaciones 2 y 3. No van a la evaluación."""

def _row(eid, station, ae, minutes, title, product):
    return {
        'id': eid,
        'station': station,
        'ae': ae,
        'minutes': minutes,
        'title': title,
        'product': product,
        'prompt': f'{title}. Producto pedido: {product}. Responde con un dato del plano, la leyenda, la ficha o las notas. Si no está en el documento, indica qué falta y a quién lo consultarías.',
    }

_M1 = [
    ('1.01', 3, 1, 90, 'Dossier sala 3°: planta R-B vs leyenda parcial', 'Lista de inconsistencias con documento y revisión'),
    ('1.02', 3, 1, 90, 'Dossier cubierta: planta rev. C vs listado rev. A', 'Consulta: qué revisión manda y por qué'),
    ('1.03', 2, 3, 90, 'Cubicación NCh353: tramos 2,5 m + 150 cm', 'Tabla en una sola unidad + total'),
    ('1.04', 2, 3, 90, 'Cubicación: mismo vano 0,80 m y 1,10 m', 'Registro de discrepancia; no promediar'),
    ('1.05', 3, 1, 60, 'Interferencia tubería/conducto sin cota', 'Marca el cruce + dato que falta (altura)'),
    ('1.06', 3, 1, 60, 'Interferencia bandeja eléctrica vs retorno HVAC', 'Consulta de coordinación con ubicación'),
    ('1.07', 3, 2, 60, 'Drenaje con origen y sin destino', 'Qué línea informa y qué no se puede afirmar'),
    ('1.08', 3, 1, 60, 'Cruce sobre línea de lácteos (sin parar el frío)', 'Decisión + evidencia de planta/sección'),
    ('1.09', 3, 2, 60, 'Sprinklers vs eje de ducto', 'Especialidades afectadas y consulta'),
    ('1.10', 3, 2, 60, 'Muro corrido vs acceso de mantención', 'Contraste planta vs terreno (dato ficticio)'),
    ('1.11', 2, 2, 60, 'Especificaciones: tipo de material', 'Extracto del dato, no del color'),
    ('1.12', 2, 2, 60, 'Especificaciones: forma de ejecutar el trabajo', '3 indicaciones rastreables al párrafo'),
    ('1.13', 2, 2, 60, 'Especificaciones: interferencia con estructura', 'Hallazgo + documento de respaldo'),
    ('1.14', 2, 2, 60, 'Especificaciones: otro servicio en el mismo cielo', 'Consulta a la especialidad citada'),
    ('1.15', 2, 1, 90, 'Informe técnico de anomalías en planos (criterio 1.4)', 'Informe: ubicación, evidencia, consulta'),
    ('1.16', 2, 2, 90, 'Informe técnico de especificaciones (criterio 2.5)', 'Informe con anomalías y TIC'),
    ('1.17', 3, 1, 60, 'Consulta: UI-01 duplicada en dos recintos', 'Consulta con etiquetas y listado'),
    ('1.18', 3, 1, 45, 'Consulta: falta el detalle D-04', 'Qué no se cubica hasta que llegue D-04'),
    ('1.19', 3, 1, 45, 'Consulta: planta C vs listado A', 'Pedido de conciliación de revisión'),
    ('1.20', 3, 2, 45, 'Consulta: control en dos muros distintos', 'Dos documentos, una pregunta'),
    ('1.21', 2, 3, 60, 'Contraste UE-01 planta vs esquema', 'Tabla etiqueta / vista / coincide'),
    ('1.22', 2, 3, 60, 'Contraste 4 UI en planta vs 3 en compra', 'Dónde queda UI-04'),
    ('1.23', 2, 3, 60, 'Contraste soporte en detalle vs listado', 'No borrar el soporte del detalle'),
    ('1.24', 2, 3, 60, 'Contraste escala 1:50 en copia reducida', 'Por qué no se mide con regla sobre el A3'),
    ('1.25', 3, 1, 60, 'Error: líquido y succión del mismo azul', 'Reconstrucción del descuido'),
    ('1.26', 3, 1, 60, 'Error: usar el archivo más liviano', 'Qué revisión se pierde'),
    ('1.27', 2, 3, 60, 'Error: promediar dos cotas del mismo vano', 'Cota inventada vs cota de proyecto'),
    ('1.28', 3, 1, 60, 'Error: firmar a las 18:00 sin registro', 'Minuta con 3 hallazgos trazables'),
    ('1.29', 2, 1, 30, 'Bitácora turno 08:15 liceo', 'Vi / consulté / pendiente'),
    ('1.30', 2, 1, 30, 'Bitácora 11:00 · llega el inspector', 'Qué dato está listo para mostrar'),
    ('1.31', 2, 2, 30, 'Bitácora 18:40 Valdivia · poca luz', 'Qué cambia en la lectura, no en el plano'),
    ('1.32', 3, 3, 30, 'Bitácora de cierre de revisión documental', 'Abierto / cerrado / no afirmable'),
]

_M2 = [
    ('2.01', 2, 1, 60, 'Protocolo TERM-01: magnitud, intervalo, punto', 'Ficha de uso antes de leer el visor'),
    ('2.02', 2, 1, 60, 'Protocolo manómetro: unidad e intervalo 50–150', 'Por qué 15 °C no se lee en ese instrumento'),
    ('2.03', 2, 1, 60, 'Protocolo visor 4,0 °C cadena de frío', 'Valor + unidad + punto de medición'),
    ('2.04', 2, 1, 60, 'Protocolo visor 21,2 °C sala', 'Copia del dato del visor, no interpretado'),
    ('2.05', 3, 1, 60, 'Protocolo comparación de dos instrumentos', 'Cuál sirve para qué intervalo'),
    ('2.06', 3, 2, 60, 'Protocolo verificación contra ficha del fabricante', 'Intervalo vs valor esperado'),
    ('2.07', 2, 3, 45, 'Bitácora lab: serie 19,8 / 20,0 / 20,2 °C', 'Fila completa por lectura'),
    ('2.08', 2, 3, 45, 'Bitácora lab: 25 sin unidad', 'Fila marcada incompleta'),
    ('2.09', 2, 3, 45, 'Bitácora lab: valor sin punto de medición', 'Qué falta para que otra persona lea'),
    ('2.10', 2, 3, 45, 'Bitácora lab: valor sin instrumento', 'No se interpreta todavía'),
    ('2.11', 3, 3, 45, 'Bitácora lab: tres puntos de la misma sala', 'Tabla punto / valor / unidad'),
    ('2.12', 3, 3, 45, 'Bitácora lab: cierre de turno de mediciones', 'Pendientes para el informe'),
    ('2.13', 3, 2, 60, 'Caso: 25 sin unidad en el registro', 'Decisión: no promediar esa fila'),
    ('2.14', 3, 2, 60, 'Caso: visor 4,0 °C y refrigerador que no se mueve', 'Qué se puede afirmar sin apagar'),
    ('2.15', 3, 2, 60, 'Caso: intervalo 50–150 vs lectura esperada 15', 'Instrumento inadecuado'),
    ('2.16', 3, 1, 60, 'Caso: resolución 0,1 °C no es exactitud', 'Separar dato de ficha vs dato inferido'),
    ('2.17', 3, 2, 60, 'Caso: dos visores, misma sala, 3 °C de diferencia', 'Qué verificar antes de concluir falla'),
    ('2.18', 2, 2, 60, 'Verificar serie 19,8–20,2 contra criterio 18–22 °C', 'Promedio, amplitud, dentro/fuera'),
    ('2.19', 2, 2, 60, 'Verificar TERM-01 intervalo −10 a 50 °C', 'La serie sí es interpretable'),
    ('2.20', 3, 2, 60, 'Verificar ficha vs visor 21,2 °C', 'Dato extraído del visor'),
    ('2.21', 3, 2, 60, 'Verificar conversión 80 cm y 0,8 m', 'Misma longitud, una unidad'),
    ('2.22', 2, 3, 90, 'Informe de mediciones del punto A', 'Informe con límites de la conclusión'),
    ('2.23', 2, 3, 90, 'Informe: qué no se concluye de la fila 25', 'Acción de verificación, no invención'),
    ('2.24', 2, 2, 45, 'Comparar dos series con el mismo criterio', 'Cuál cumple y con qué evidencia'),
    ('2.25', 2, 2, 45, 'Comparar criterio de aula vs cámara 4 °C', 'No usar el mismo intervalo'),
    ('2.26', 3, 2, 45, 'Comparar tres lecturas y detectar la incompleta', 'Marca la fila que no se lee'),
    ('2.27', 3, 3, 45, 'Comparar registro vs ficha vs visor', 'Tres columnas, una discrepancia'),
    ('2.28', 3, 3, 60, 'Error: borrar 28,1 °C para «arreglar» el promedio', 'Reconstrucción del descuido'),
    ('2.29', 3, 3, 60, 'Error: anotar 25 y asumir °C', 'Por qué no se firma esa fila'),
    ('2.30', 3, 1, 45, 'Error: usar TERM-01 fuera de intervalo', 'Qué instrumento pedir'),
    ('2.31', 3, 1, 30, 'Contexto: 14:00 Antofagasta, visor +3 °C', 'Cambia el contexto, no el criterio'),
    ('2.32', 3, 1, 30, 'Contexto: misma sala, otro instrumento', 'Qué dato hay que volver a registrar'),
    ('2.33', 2, 1, 30, 'Contexto: laboratorio vs terreno', 'Qué se pierde al salir del lab'),
    ('2.34', 2, 3, 30, 'Contexto: cierre de jornada de mediciones', 'Pendiente para mañana'),
    ('2.35', 3, 2, 60, 'Caso extra: farmacia 4,0 °C y soporte sísmico', 'Medición no autoriza a quitar el soporte'),
    ('2.36', 3, 2, 60, 'Caso extra: packing Rengo, dos cotas del vano', 'No promediar; pedir confirmación'),
]

_M3 = [
    ('3.01', 3, 2, 90, 'Armado documental tramo A 2,5 m', 'Lista de materiales + uniones + prueba pendiente'),
    ('3.02', 3, 2, 90, 'Armado documental tramo B 150 cm (cruzar viga)', 'No unir hasta tener cota de altura'),
    ('3.03', 3, 2, 90, 'Armado documental tramo C 3,0 m', 'Cubicación neta de C'),
    ('3.04', 3, 3, 90, 'Armado: preparar puesto → unir → hermeticidad', 'Orden de obra con evidencia de cada paso'),
    ('3.05', 2, 1, 90, 'Armado: soldadura blanda según normativa (documental)', 'Qué se verifica; qué no se simula (soplete)'),
    ('3.06', 2, 1, 90, 'Armado: emballetado vs soldadura fuerte', 'Decisión según material del tramo'),
    ('3.07', 3, 3, 90, 'Armado extra: red de la sala del M1 (mismo liceo)', 'Reusa etiquetas UE-01 / UI-01'),
    ('3.08', 2, 3, 90, 'Cubicación red: A+B+C y reserva 10 %', 'Neta, reserva, total; unidad única'),
    ('3.09', 2, 3, 90, 'Cubicación: C-01 en planta y detalle (una pieza)', 'No duplicar el accesorio'),
    ('3.10', 2, 3, 90, 'Cubicación: tramos en m y cm mezclados', 'Tabla unificada'),
    ('3.11', 3, 2, 60, 'Interferencia: cruce B sin cota de altura', 'Consulta de altura con ubicación'),
    ('3.12', 3, 2, 60, 'Interferencia: bandeja eléctrica en el eje HVAC', 'No desviar el ducto por cuenta propia'),
    ('3.13', 3, 2, 60, 'Interferencia: viga vs tramo B', 'Planta no prueba colisión'),
    ('3.14', 3, 2, 60, 'Interferencia: sprinklers', 'Especialidades y dato que falta'),
    ('3.15', 3, 3, 60, 'Interferencia: espacio reservado a otro proyecto', 'Consulta de coordinación'),
    ('3.16', 3, 3, 60, 'Interferencia: cielo técnico del mall', 'Quién cierra primero y con qué evidencia'),
    ('3.17', 2, 3, 60, 'Hermeticidad: registro de prueba (no soplete)', 'Acta: tramo, resultado, pendiente'),
    ('3.18', 2, 3, 60, 'Hermeticidad: qué falta para firmar el tramo B', 'Cota de altura como prerrequisito'),
    ('3.19', 3, 3, 60, 'Hermeticidad: tres tramos, una prueba pendiente', 'Estado por tramo'),
    ('3.20', 3, 1, 60, 'Hermeticidad: evidencia fotográfica de unión (simulación)', 'Qué se ve y qué no se afirma'),
    ('3.21', 2, 1, 45, 'NCh3241: soldar sin EPP', 'Reconstrucción del descuido'),
    ('3.22', 2, 1, 45, 'NCh3241: puesto de trabajo', 'Lista de condiciones antes de unir'),
    ('3.23', 3, 1, 45, 'NCh3241: obra de noche, cobre frío', 'Qué cambia en la unión (documental)'),
    ('3.24', 2, 1, 60, 'Unión: soldadura fuerte · cobre', 'Par material–proceso con dato del plano'),
    ('3.25', 2, 1, 60, 'Unión: soldadura blanda · cuando aplica', 'Criterio escrito, no receta'),
    ('3.26', 2, 2, 60, 'Unión: emballetado · hojalatería', 'Par pieza–función'),
    ('3.27', 3, 2, 60, 'Unión: no mezclar procesos en el mismo tramo sin dato', 'Qué especificación lo confirma'),
    ('3.28', 3, 3, 30, 'Bitácora red: uniones hechas', 'Vi / hice / pendiente'),
    ('3.29', 3, 3, 30, 'Bitácora red: prueba abierta', 'Tramo B no se cierra'),
    ('3.30', 2, 3, 30, 'Bitácora red: consulta de altura', 'Texto de la consulta'),
    ('3.31', 2, 2, 30, 'Bitácora red: cierre de jornada en obra', 'Qué queda para el otro turno'),
    ('3.32', 3, 2, 90, 'Transferencia: red de la sala 3° del M1', 'Mismas etiquetas, nueva red'),
    ('3.33', 3, 3, 90, 'Transferencia: cubicación que usa el plano del M1', 'Cantidades rastreables a tramos M1'),
    ('3.34', 3, 1, 90, 'Transferencia: interferencia sobre el drenaje del M1', 'El destino del drenaje sigue abierto'),
    ('3.35', 3, 2, 45, 'Contexto: Punta Arenas, cobre frío', 'Cambia la lectura de la unión, no el trazado'),
    ('3.36', 3, 2, 45, 'Contexto: obra de noche', 'Qué dato se pierde sin luz'),
    ('3.37', 2, 3, 45, 'Contexto: capataz pide medidas ya (copia A3)', 'No medir sobre copia reducida'),
    ('3.38', 2, 1, 45, 'Contexto: electricista cierra bandeja mañana', 'Consulta hoy, no desvío propio'),
]

_M4 = [
    ('4.01', 3, 1, 90, 'Condiciones previas EQ-02: ficha vs recinto', 'Lista: cabe / no cabe / no se afirma'),
    ('4.02', 3, 1, 90, 'Condiciones previas: 24 cm vs 30 cm de acceso', 'Diferencia y consulta'),
    ('4.03', 2, 1, 90, 'Condiciones previas: CTRL-01 vs CTRL-02 recibido', 'No firmar compatibilidad'),
    ('4.04', 2, 2, 90, 'Condiciones previas: obras civiles incompletas', 'Qué debe existir antes del montaje'),
    ('4.05', 3, 2, 60, 'Equipo recibido vs dossier EQ-02', 'Coincide modelo; falta acceso'),
    ('4.06', 3, 3, 60, 'Control recibido CTRL-02 vs CTRL-01 del proyecto', 'Consulta de compatibilidad'),
    ('4.07', 3, 2, 60, 'Split 9000 BTU a 8 cm del rack', 'Cabe el equipo; no hay mantención'),
    ('4.08', 3, 2, 60, 'Cassette UI-01 ya en techo, leyenda incompleta', 'Reusa hallazgo M1'),
    ('4.09', 3, 1, 60, 'Tres UE en planta C, dos en listado A', 'No comprar con el listado viejo'),
    ('4.10', 2, 2, 90, 'Plan de montaje: secuencia de 20+15 min', 'Orden y duración del bloque'),
    ('4.11', 2, 2, 90, 'Plan de montaje: recursos y no apagar el rack', 'Plan que conserva el servicio de TI'),
    ('4.12', 2, 2, 90, 'Plan de montaje: cubierta de hotel, check-in viernes', 'Qué se puede montar con la revisión C'),
    ('4.13', 3, 2, 90, 'Plan de montaje: gimnasio 4 UI vs 3 en compra', 'Dónde queda el cuarto cuadrante'),
    ('4.14', 3, 2, 60, 'Acceso lateral 24 vs 30 cm (closet servidores)', 'No certificar mantención'),
    ('4.15', 3, 2, 60, 'Acceso: equipo cabe y aun así falta espacio', 'Dato de ficha, no de apariencia'),
    ('4.16', 2, 2, 60, 'Acceso: filtro que no se puede cambiar', 'Consecuencia de firmar el 24 cm'),
    ('4.17', 2, 3, 60, 'Control automático: conector ≠ compatibilidad', 'Dato de documentación'),
    ('4.18', 2, 3, 60, 'Control: muro este vs muro oeste (sol de tarde)', 'Cuál documento manda'),
    ('4.19', 3, 3, 60, 'Control: sensor al sol o detrás del escritorio', 'Riesgo de cada muro'),
    ('4.20', 3, 3, 60, 'Control: ficha vs conector recibido', 'Consulta, no instalación'),
    ('4.21', 3, 2, 60, 'Estado de entrega: EQ-02 verificado / acceso pendiente', 'Acta de recepción parcial'),
    ('4.22', 3, 2, 60, 'Estado de entrega: CTRL no compatible', 'Abierto / no afirmable'),
    ('4.23', 2, 3, 60, 'Estado de entrega: tres hallazgos del M1 que siguen abiertos', 'Cita etiqueta duplicada, drenaje, D-04'),
    ('4.24', 2, 3, 60, 'Estado de entrega: red del M3, prueba B pendiente', 'No dar conformidad de equipos sobre red abierta'),
    ('4.25', 3, 1, 60, 'Estado de entrega: cierre documental del liceo', 'Qué se entrega al inspector'),
    ('4.26', 3, 1, 60, 'Estado de entrega: firma 18:00 vs registro trazable', 'Minuta, no WhatsApp'),
    ('4.27', 3, 1, 90, 'Citar M1: leyenda incompleta de la sala 3°', 'El montaje no cierra esa leyenda'),
    ('4.28', 3, 2, 90, 'Citar M2: visor 4 °C no autoriza a mover el equipo', 'Medición ≠ permiso de ubicación'),
    ('4.29', 3, 3, 90, 'Citar M3: cruce B sin cota, no montar sobre interferencia', 'Dependencia de red abierta'),
    ('4.30', 3, 2, 60, 'Recinto rack / servidores', 'Plan que no apaga el correo'),
    ('4.31', 3, 2, 60, 'Recinto cassette de aula', 'UI-01 vs leyenda del M1'),
    ('4.32', 3, 1, 60, 'Recinto cubierta de hotel', 'Tres UE, listado de dos'),
    ('4.33', 3, 1, 60, 'Recinto gimnasio municipal', 'Cuatro cuadrantes, tres equipos'),
    ('4.34', 3, 2, 45, 'Presión: TI no apaga el rack', 'Decisión sin cortar servicio'),
    ('4.35', 3, 2, 45, 'Presión: cadena de frío 4,0 °C', 'No mover el refrigerador'),
    ('4.36', 2, 3, 45, 'Presión: check-in el viernes', 'Qué se puede firmar hoy'),
]

_BY_MODULE = {1: _M1, 2: _M2, 3: _M3, 4: _M4}


def encargos_for(mid):
    rows = _BY_MODULE.get(int(mid or 0)) or []
    items = [_row(*r) for r in rows]
    minutes = sum(i['minutes'] for i in items)
    return {
        'items': items,
        'count': len(items),
        'minutes': minutes,
        'hours': round(minutes / 60, 1),
    }
