import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync(new URL('../static/app.js',import.meta.url),'utf8');
let reset,now=10000,reduced=false;
const attributes={},mascot={dataset:{},closest:()=>({setAttribute:(k,v)=>attributes[k]=v})};
const events={},fab={matches:()=>false,querySelector:()=>mascot};
const document={hidden:false,activeElement:{matches:()=>false},documentElement:{classList:{contains:()=>reduced}},body:{classList:{contains:()=>false}},querySelector:s=>s==='.tools-fab.is-dragging'?null:s==='.tools-fab'?fab:mascot,addEventListener:(k,v)=>events[k]=v};
const scope=vm.createContext({window:{},document,Date:{now:()=>now},Math,Uint8Array,matchMedia:()=>({matches:reduced}),clearTimeout:()=>{},setTimeout:fn=>{reset=fn;return 1;}});
vm.runInContext(source.slice(source.indexOf('let nubiEmotionTimer;'),source.indexOf('function toolsFabClamp')),scope);
let bindings=0;scope.bindNubiCloudMotion=()=>bindings++;
for(const [input,expected] of Object.entries({idle:'idle',happy:'happy',listening:'listening',speaking:'speaking',turn:'happy',wave:'happy',celebrate:'happy',think:'listening',sad:'idle',surprised:'idle'})){
 scope.setNubiEmotion(input);assert.equal(mascot.dataset.emotion,expected);assert.equal(attributes['data-emotion'],expected);
}
scope.setNubiEmotion('invalid');assert.equal(mascot.dataset.emotion,'idle');
scope.bindNubiEmotions();scope.bindNubiEmotions();assert.equal(bindings,1);
const button={matches:()=>false,closest:s=>['.tools-fab-btn','[data-action="tools-fab-toggle"]'].includes(s)?fab:null};
events.click({target:button});assert.equal(mascot.dataset.emotion,'happy');
reset();assert.equal(mascot.dataset.emotion,'idle');
events['nubi-emotion']({detail:{emotion:'speaking'}});assert.equal(mascot.dataset.emotion,'speaking');
reduced=true;events['nubi-emotion']({detail:{emotion:'happy'}});assert.equal(mascot.dataset.emotion,'idle');
reduced=false;document.hidden=true;events['nubi-emotion']({detail:{emotion:'speaking'}});assert.equal(mascot.dataset.emotion,'idle');
document.hidden=false;
assert.doesNotMatch(source.slice(source.indexOf('function bindNubiEmotions'),source.indexOf('function nubiContourPath')),/setInterval|animationend|new Image/);
const markup=scope.nubiCloudMarkup('nubi-robot');
assert.equal((markup.match(/class="nubi-eye"/g)||[]).length,2);
assert.match(markup,/src="\/static\/nubi-cloud-reference.png"/);
assert.match(markup,/fill="#1677ff"/);
const path=scope.nubiContourPath(0),later=scope.nubiContourPath(.04);
assert.notEqual(path,later);assert.equal((path.match(/C/g)||[]).length,12);assert.ok(path.endsWith('Z'));
for(let t=0;t<10;t+=.03){
 const values=scope.nubiContourPath(t).match(/-?\d+\.\d+/g).map(Number);
 assert.ok(values.every(n=>Number.isFinite(n)&&n>=8&&n<=112),'Contour stays inside its fixed viewBox');
 const next=scope.nubiContourPath(t+.032).match(/-?\d+\.\d+/g).map(Number);
 assert.ok(values.every((n,i)=>Math.abs(n-next[i])<1.5),'Contour changes continuously without sudden jumps');
}
const css=fs.readFileSync(new URL('../static/aula-soft-depth.css',import.meta.url),'utf8').split('/* Flat cloud replaces')[1];
assert.match(css,/background:none!important;filter:none!important;box-shadow:none!important;animation:none!important;transform:none!important/);
assert.match(css,/transition:transform 300ms/);assert.match(css,/120ms/);assert.match(css,/prefers-reduced-motion/);
assert.doesNotMatch(css,/@keyframes|drop-shadow|opacity:0|scale\(/);
assert.doesNotMatch(source.slice(source.indexOf('function bindNubiCloudMotion'),source.indexOf('function toolsFabClamp')),/getUserMedia/);
const panel={style:{setProperty(k,v){this[k]=v;}},getBoundingClientRect:()=>({width:380,height:452})};
const anchor={querySelector:()=>panel,getBoundingClientRect:()=>({left:273,top:63,bottom:195})};
scope.window.innerWidth=434;scope.window.innerHeight=668;
vm.runInContext(source.slice(source.indexOf('function toolsFabPlacePanel('),source.indexOf('function bindToolsFabDrag(')),scope);
scope.toolsFabPlacePanel(anchor);assert.equal(Number.parseFloat(panel.style.left)+273,46);
assert.ok(Number.parseFloat(panel.style.top)+63>=8);
const buttonEvents={},windowEvents={},position=[];
let saves=0,closed=0;
const dragButton={dataset:{},setAttribute:()=>{},addEventListener:(k,v)=>buttonEvents[k]=v,setPointerCapture:()=>{},releasePointerCapture:()=>{}};
const dragFab={dataset:{},classList:{add:()=>{},remove:()=>{}},querySelector:()=>dragButton,getBoundingClientRect:()=>({left:100,top:100,width:132,height:132})};
scope.window.addEventListener=(k,v)=>windowEvents[k]=v;
scope.window.removeEventListener=k=>delete windowEvents[k];
scope.closeToolsFab=()=>closed++;
scope.toolsFabApplyPos=(_,p)=>position.push(p);
scope.toolsFabSavePos=()=>saves++;
scope.toolsFabClamp=(x,y)=>({x,y});
vm.runInContext(source.slice(source.indexOf('function bindToolsFabDrag('),source.indexOf('function bindToolsFabResize(')),scope);
scope.bindToolsFabDrag(dragFab);
buttonEvents.pointerdown({pointerType:'mouse',button:0,clientX:100,clientY:100,pointerId:1});
windowEvents.pointermove({clientX:140,clientY:130,pointerId:1,preventDefault:()=>{}});
windowEvents.pointerup({pointerId:1});
assert.equal(position.at(-1).x,140);assert.equal(position.at(-1).y,130);assert.equal(saves,1);
assert.equal(dragFab.dataset.skipClick,'1');assert.ok(closed>0);
buttonEvents.keydown({altKey:true,key:'ArrowRight',preventDefault:()=>{}});
assert.equal(position.at(-1).x,120);assert.equal(saves,2);
assert.match(source,/toolsFabRestore\(fab\);bindToolsFabDrag\(fab\)/);
console.log('Nubi: flat cloud, bounded contour, eye shapes, legacy events, reduced motion, assistant panel, drag, saved position and keyboard movement verified.');
