import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync(new URL('../static/app.js',import.meta.url),'utf8');
let reset,occasional,intervalMs,timeoutMs,now=10000,typing=false,reduced=false,open=false,dragging=false;
const attributes={},mascot={dataset:{},matches:selector=>selector==='.nubi-robot',closest:()=>({setAttribute:(key,value)=>attributes[key]=value})};
const events={};
const fab={matches:()=>open||dragging,querySelector:()=>mascot};
const document={hidden:false,activeElement:{matches:()=>typing},documentElement:{classList:{contains:()=>reduced}},body:{classList:{contains:()=>false}},querySelector:selector=>selector==='.tools-fab'?fab:selector==='.tools-fab.is-dragging'?(dragging?fab:null):mascot,addEventListener:(name,listener)=>events[name]=listener};
const scope=vm.createContext({window:{},document,Date:{now:()=>now},matchMedia:()=>({matches:reduced}),
  clearTimeout:()=>{},setTimeout:(fn,ms)=>{reset=fn;timeoutMs=ms;return 1;},setInterval:(fn,ms)=>{occasional=fn;intervalMs=ms;return 1;}});
vm.runInContext(source.slice(source.indexOf('let nubiEmotionTimer;'),source.indexOf('function toolsFabClamp')),scope);
for(const emotion of ['idle','wave','celebrate','sad','think','surprised','turn']){
  scope.setNubiEmotion(emotion);
  assert.equal(mascot.dataset.emotion,emotion);
  assert.equal(attributes['data-emotion'],emotion);
}
reset();assert.equal(mascot.dataset.emotion,'idle');
scope.setNubiEmotion('invalid');assert.equal(mascot.dataset.emotion,'idle');
scope.bindNubiEmotions();
assert.equal(intervalMs,35000);
occasional();assert.equal(mascot.dataset.emotion,'turn');assert.equal(timeoutMs,2500);
events.animationend({target:mascot,animationName:'nubi-body-turn'});
assert.equal(mascot.dataset.emotion,'idle');
occasional();assert.equal(mascot.dataset.emotion,'wave');assert.equal(timeoutMs,2300);
events.animationend({target:mascot,animationName:'nubi-body-wave'});
assert.equal(mascot.dataset.emotion,'idle');
typing=true;
occasional();assert.equal(mascot.dataset.emotion,'idle');
typing=false;document.hidden=true;
occasional();assert.equal(mascot.dataset.emotion,'idle');
document.hidden=false;reduced=true;
occasional();assert.equal(mascot.dataset.emotion,'idle');
reduced=false;open=true;
occasional();assert.equal(mascot.dataset.emotion,'idle');
open=false;dragging=true;
occasional();assert.equal(mascot.dataset.emotion,'idle');
dragging=false;
const button={matches:()=>false,closest:selector=>['.tools-fab-btn','[data-action="tools-fab-toggle"]'].includes(selector)?fab:null};
events.pointerover({target:button});assert.equal(mascot.dataset.emotion,'wave');
reset();now+=2000;
events.pointerover({target:button});assert.equal(mascot.dataset.emotion,'idle');
now+=7000;
events.focusin({target:button});assert.equal(mascot.dataset.emotion,'wave');
events.focusin({target:{matches:()=>true}});assert.equal(mascot.dataset.emotion,'idle');
events.click({target:button});assert.equal(mascot.dataset.emotion,'wave');
document.hidden=true;events.visibilitychange();assert.equal(mascot.dataset.emotion,'idle');
document.hidden=false;reduced=true;
events.click({target:button});assert.equal(mascot.dataset.emotion,'idle');
reduced=false;
events['nubi-emotion']({detail:{emotion:'celebrate'}});
assert.equal(mascot.dataset.emotion,'celebrate');
assert.match(source,/data-action="tools-fab-toggle"[^>]*aria-expanded="false"/);
assert.doesNotMatch(source,/src="\/static\/agente-nubi-chat-luminoso/);
const css=fs.readFileSync(new URL('../static/support-tools.css',import.meta.url),'utf8');
assert.match(css,/prefers-reduced-motion:reduce/);
assert.match(css,/\.reduce-motion \.tools-fab \.nubi-robot/);
const depth=fs.readFileSync(new URL('../static/aula-soft-depth.css',import.meta.url),'utf8');
assert.match(depth,/background-size:400% 400%!important/);
assert.match(depth,/background-position:var\(--nubi-frame-x\) var\(--nubi-frame-y\)!important/);
assert.match(depth,/@keyframes nubi-body-turn/);
assert.match(depth,/@keyframes nubi-body-wave/);
const sheet=fs.readFileSync(new URL('../static/nubi-body-poses-v4.png',import.meta.url));
assert.equal(sheet.readUInt32BE(16),sheet.readUInt32BE(20),'Los cuadros deben ser cuadrados para no deformar el cuerpo');
assert.ok(sheet.readUInt32BE(16)>=1024);

const panel={style:{setProperty(key,value,priority){this[key]=value;this.priority=priority}},getBoundingClientRect:()=>({width:380,height:452})};
const anchor={querySelector:()=>panel,getBoundingClientRect:()=>({left:273,top:63,bottom:169})};
scope.window.innerWidth=434;scope.window.innerHeight=668;
vm.runInContext(source.slice(source.indexOf('function toolsFabPlacePanel('),source.indexOf('function bindToolsFabDrag(')),scope);
scope.toolsFabPlacePanel(anchor);
assert.equal(Number.parseFloat(panel.style.left)+273,46);
assert.equal(Number.parseFloat(panel.style.top)+63,181);
assert.equal(panel.style['max-height'],'min(70vh, 520px, 479px)');
assert.equal(panel.style.priority,'important');
document.documentElement.clientWidth=418;
scope.toolsFabPlacePanel(anchor);
assert.equal(Number.parseFloat(panel.style.left)+273,30,'El menu no debe quedar detras de la barra de desplazamiento');
delete document.documentElement.clientWidth;
scope.window.innerWidth=320;scope.window.innerHeight=568;
panel.getBoundingClientRect=()=>({width:292,height:390});
anchor.getBoundingClientRect=()=>({left:200,top:430,bottom:536});
scope.toolsFabPlacePanel(anchor);
assert.equal(Number.parseFloat(panel.style.left)+200,20);
assert.equal(Number.parseFloat(panel.style.top)+430,28);
console.log('Nubi: poses proporcionadas, giro y saludo, reposo, accesibilidad, pausa al escribir y menu dentro de la pantalla verificados.');
