const {readFileSync}=require('node:fs');
const vm=require('node:vm'),assert=require('node:assert/strict');
const storage=new Map();
const ctx=vm.createContext({localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},auth:{user:{id:1,role:'student'}},current:{id:1,state:{context:'',ae:{},cases:{},scene:null,exam:null,draft:{},reflection:'',plan:'',closed:false}},ae:0,step:0,caseIndex:0,examDraft:{}});
vm.runInContext(readFileSync('static/drafts.js','utf8')+';this.drafts=localDrafts',ctx);
const d=ctx.drafts;
d.write('context',{text:'Texto sin entregar'});
assert.equal(d.read('context').text,'Texto sin entregar');
ctx.auth.user.id=2;assert.equal(d.read('context'),null);
ctx.auth.user.id=1;ctx.current.id=2;assert.equal(d.read('context'),null);
ctx.current.id=1;assert.equal(d.read('context').text,'Texto sin entregar');
ctx.current.state.context='Respuesta entregada';assert.equal(d.read('context'),null);
assert.equal(Object.keys(ctx.current.state.ae).length,0);
d.write('ae:0:0',{text:'Primer paso'});d.write('ae:0:1',{text:'Segundo paso'});
assert.equal(d.read('ae:0:0').text,'Primer paso');assert.equal(d.read('ae:0:1').text,'Segundo paso');
d.write('exam',{answers:{0:2,24:1,25:2,3:9},development:'Borrador examen'});d.restoreExam();
assert.equal(JSON.stringify(ctx.examDraft),JSON.stringify({answers:{0:2,24:1},development:'Borrador examen'}));
ctx.current.state.exam={score:20};assert.equal(d.read('exam'),null);
ctx.current.state.closed=true;d.write('close',{plan:'No debe guardarse'});assert.equal(storage.has(d.key('close')),false);
ctx.current.state.closed=false;ctx.auth.user.role='teacher';assert.equal(d.read('ae:0:0'),null);
ctx.auth.user.role='student';storage.set(d.key('scene'),'broken json');assert.equal(d.read('scene'),null);
let warning='';d.status=(f,s)=>warning=s;ctx.localStorage.setItem=()=>{throw Error('quota')};
assert.doesNotThrow(()=>d.write('context',{text:'Retenido en pantalla'},{}));assert.match(warning,/No se pudo guardar/);
console.log('Draft checks passed: isolation, stale evidence, exam validation, closure, teacher preview, corrupt storage and storage failure.');
